name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run:  docker build -t noxxspring/football-livescore .
      - name: Publish image to docker hub
        run:  docker push noxxspring/football-livescore:latest

  deploy:
    needs: build
    runs-on: [aws_ec2]
    steps:
      - name: Pull Image from docker hub
        run:  docker pull noxxspring/football-livescore:latest
      - name: Delete old container
        run:  docker rm -f livescore-container
      - name:  Run docker container
        run:  docker run -d -p 8080:8080 --name livescore-container noxxspring/football-livescore